import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import sharp from 'sharp';
import { afterAll, afterEach, beforeEach, describe, expect, it } from 'vitest';
import { getDatabase } from '@/shared/infra/database';
import { fixedClock, uuidv7 } from '@/shared/kernel';
import { createPendingMedia, transition } from '@/modules/media/domain/media';
import { PrismaMediaRepository } from '@/modules/media/infrastructure/prisma-media-repository';
import { LocalMediaBlobStore } from '@/modules/media/infrastructure/local-media-blob-store';
import { SharpThumbnailGenerator } from '@/modules/media/infrastructure/sharp-thumbnail-generator';
import { processThumbnailJob } from '@/modules/media/application/process-thumbnail';

/**
 * Exercises the real orchestration against real Postgres and a real (if
 * filesystem-backed) blob store — the codebase's convention throughout is to
 * test application logic against real adapters rather than fakes (see
 * `tests/integration/verse-routes.test.ts` and friends), because a fake
 * repository cannot say whether the actual SQL and the actual generated bytes
 * agree with what the job assumes about them.
 */
const DATABASE_URL = process.env.DATABASE_URL;
const NOW = new Date('2026-09-09T12:00:00.000Z');
const clock = fixedClock(NOW);

const media = new PrismaMediaRepository();
const generator = new SharpThumbnailGenerator();

let storageRoot: string;
let blobStore: LocalMediaBlobStore;

describe.skipIf(!DATABASE_URL)('processThumbnailJob against real Postgres', () => {
  beforeEach(async () => {
    await getDatabase()!.$executeRawUnsafe('DELETE FROM media.media');
    storageRoot = await mkdtemp(join(tmpdir(), 'process-thumbnail-'));
    blobStore = new LocalMediaBlobStore(storageRoot);
  });

  afterEach(async () => {
    await rm(storageRoot, { recursive: true, force: true });
  });

  afterAll(async () => {
    await getDatabase()?.$disconnect();
  });

  const deps = () => ({ media, blobStore, generator, clock });

  const processingMedia = async (ownerId: string) => {
    const row = createPendingMedia({
      ownerId,
      contentType: 'image/jpeg',
      declaredSizeBytes: 400_000,
      clock,
    });
    await media.create(row);
    const processing = transition(row, 'processing', clock);
    if (!processing.ok) throw new Error('unreachable');
    await media.update(processing.value, row.version);
    return processing.value;
  };

  it('reads the original, writes both variants, and marks the row ready', async () => {
    const ownerId = uuidv7(NOW.getTime());
    const row = await processingMedia(ownerId);
    const original = await sharp({
      create: { width: 800, height: 600, channels: 3, background: 'green' },
    })
      .jpeg()
      .toBuffer();
    await blobStore.writeBuffer(row.storageKey, original);

    await processThumbnailJob(row.id, deps());

    const found = await media.findById(row.id);
    expect(found?.status).toBe('ready');
    expect(found?.version).toBe(row.version + 1);

    const variants = await media.variantsFor(row.id);
    expect(variants.map((v) => v.kind).sort()).toEqual(['medium', 'thumb']);

    for (const variant of variants) {
      const bytes = await blobStore.readBuffer(variant.storageKey);
      expect(bytes).not.toBeNull();
      const meta = await sharp(bytes!).metadata();
      expect(meta.format).toBe('jpeg');
      expect(meta.width).toBe(variant.width);
      expect(meta.height).toBe(variant.height);
      expect(variant.sizeBytes).toBe(bytes!.length);
    }
  });

  it('marks the row failed, without throwing, when the original is missing from storage', async () => {
    const ownerId = uuidv7(NOW.getTime());
    const row = await processingMedia(ownerId);
    // Deliberately never written to blobStore — simulates a confirm that
    // raced ahead of, or outlived, the actual upload.

    await expect(processThumbnailJob(row.id, deps())).resolves.toBeUndefined();

    const found = await media.findById(row.id);
    expect(found?.status).toBe('failed');
    expect(await media.variantsFor(row.id)).toEqual([]);
  });

  it('is a no-op for a row that is not in processing', async () => {
    const ownerId = uuidv7(NOW.getTime());
    const row = createPendingMedia({
      ownerId,
      contentType: 'image/jpeg',
      declaredSizeBytes: 400_000,
      clock,
    });
    await media.create(row);
    // Still `pending` — no upload has been confirmed yet.

    await processThumbnailJob(row.id, deps());

    const found = await media.findById(row.id);
    expect(found?.status).toBe('pending');
    expect(found?.version).toBe(0);
  });

  it('is a no-op for a media id that does not exist', async () => {
    await expect(processThumbnailJob(uuidv7(), deps())).resolves.toBeUndefined();
  });

  it('is idempotent against a second delivery of the same job', async () => {
    const ownerId = uuidv7(NOW.getTime());
    const row = await processingMedia(ownerId);
    const original = await sharp({
      create: { width: 400, height: 300, channels: 3, background: 'yellow' },
    })
      .jpeg()
      .toBuffer();
    await blobStore.writeBuffer(row.storageKey, original);

    await processThumbnailJob(row.id, deps());
    const firstPass = await media.findById(row.id);

    // A second, redundant delivery (Cloud Tasks at-least-once, or a retried
    // local call) must not fail, and must not move a `ready` row anywhere.
    await expect(processThumbnailJob(row.id, deps())).resolves.toBeUndefined();
    const secondPass = await media.findById(row.id);

    expect(secondPass).toEqual(firstPass);
    expect(await media.variantsFor(row.id)).toHaveLength(2);
  });
});
